import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { formatDateTime } from "@/lib/format";
import { StatusBadge } from "@/components/admin/status-badge";
import { EmptyState } from "@/components/admin/empty-state";
import { openConversation } from "@/lib/actions/conversations";
import { unreadConversationIds } from "@/lib/queries/conversations";
import { requireUser } from "@/lib/auth/session";

// Un fil par élève et par session. Les fils sont créés à la volée : par le
// moteur de process au premier mail, ou ici au premier message du formateur.
export async function ConversationsSection({ sessionId }: { sessionId: string }) {
  const enrollments = await prisma.enrollment.findMany({
    where: { sessionId },
    orderBy: { enrolledAt: "asc" },
    select: { user: { select: { id: true, name: true, email: true } } },
  });
  if (enrollments.length === 0) {
    return <EmptyState title="Aucun élève inscrit">Les fils de discussion apparaîtront dès la première inscription.</EmptyState>;
  }

  const conversations = await prisma.conversation.findMany({
    where: { sessionId },
    select: {
      id: true,
      userId: true,
      _count: { select: { messages: true } },
      messages: { orderBy: { sentAt: "desc" }, take: 1, select: { body: true, sentAt: true, senderId: true, autoGenerated: true } },
    },
  });
  const byUser = new Map(conversations.map((c) => [c.userId, c]));
  const me = await requireUser();
  const unread = await unreadConversationIds(conversations.map((c) => c.id), me.id);

  return (
    <ol className="divide-y rounded-md border">
      {enrollments.map(({ user }) => {
        const conv = byUser.get(user.id);
        // Fils antérieurs à l'ouverture systématique : on les crée à l'ouverture.
        if (!conv) {
          return (
            <li key={user.id}>
              <form action={openConversation.bind(null, sessionId, user.id)}>
                <button type="submit" className="flex w-full items-center justify-between gap-4 px-4 py-3 text-left text-sm transition-colors hover:bg-surface">
                  <span className="font-medium">{user.name}</span>
                  <span className="shrink-0 text-xs text-foreground-tertiary">Ouvrir le fil</span>
                </button>
              </form>
            </li>
          );
        }
        const last = conv.messages[0] ?? null;
        // « À lire » : un message que je n'ai pas encore ouvert.
        const waiting = unread.has(conv.id);
        const excerpt = last ? last.body.replace(/[*_#>`]/g, " ").replace(/\s+/g, " ").trim().slice(0, 110) : null;
        return (
          <li key={user.id}>
            <Link
              href={`/admin/conversations/${conv.id}`}
              className="flex items-start justify-between gap-4 px-4 py-3 text-sm transition-colors hover:bg-surface"
            >
              <span className="min-w-0">
                <span className="flex flex-wrap items-center gap-2 font-medium">
                  {user.name}
                  {waiting ? <StatusBadge tone="orange">À lire</StatusBadge> : null}
                </span>
                <span className="mt-0.5 block truncate text-xs text-foreground-secondary">
                  {excerpt && last ? `${last.autoGenerated ? "Automatique · " : ""}${excerpt}` : "Aucun message — ouvrir pour écrire"}
                </span>
              </span>
              <span className="shrink-0 text-right text-xs text-foreground-tertiary">
                {last ? <>{formatDateTime(last.sentAt)}<span className="block">{conv._count.messages} message(s)</span></> : "—"}
              </span>
            </Link>
          </li>
        );
      })}
    </ol>
  );
}
