import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { formatDateTime } from "@/lib/format";
import { StatusBadge } from "@/components/admin/status-badge";
import { EmptyState } from "@/components/admin/empty-state";

type Meta = { sentTo?: string; sandbox?: boolean; providerId?: string | null };

// Journal des messages d'une session : ce que la plateforme a envoyé, à qui,
// et vers quelle adresse le mail est réellement parti (bac à sable compris).
export async function MessagesSection({ sessionId }: { sessionId: string }) {
  const messages = await prisma.message.findMany({
    where: { conversation: { sessionId } },
    include: { conversation: { include: { user: { select: { id: true, name: true, email: true } } } }, sender: { select: { name: true } } },
    orderBy: { sentAt: "desc" },
    take: 50,
  });

  if (messages.length === 0) {
    return <EmptyState title="Aucun message envoyé">Les envois apparaîtront ici, avec leur destinataire réel.</EmptyState>;
  }

  return (
    <ol className="divide-y rounded-md border">
      {messages.map((m) => {
        const meta = (m.attachments ?? {}) as Meta;
        const subject = m.body.startsWith("**") ? m.body.slice(2, m.body.indexOf("**", 2)) : m.body.slice(0, 80);
        return (
          <li key={m.id} className="px-3 py-2.5 text-sm">
            <div className="flex flex-wrap items-start justify-between gap-2">
              <div className="min-w-0">
                <p className="font-medium">{subject}</p>
                <p className="text-xs text-foreground-secondary">
                  Fil de <Link href={`/admin/eleves/${m.conversation.user.id}`} className="hover:underline">{m.conversation.user.name}</Link>
                  {" · "}{formatDateTime(m.sentAt)}
                  {" · "}{m.autoGenerated ? "envoyé par le moteur de process" : `envoyé par ${m.sender?.name ?? "—"}`}
                </p>
                {meta.sentTo ? (
                  <p className="mt-0.5 text-xs text-foreground-tertiary">
                    Destinataire prévu : {m.conversation.user.email} · réellement envoyé à : {meta.sentTo}
                  </p>
                ) : null}
              </div>
              <span className="flex shrink-0 items-center gap-1.5">
                {m.autoGenerated ? <StatusBadge tone="blue">Auto</StatusBadge> : null}
                {meta.sandbox ? <StatusBadge tone="yellow">Bac à sable</StatusBadge> : null}
              </span>
            </div>
          </li>
        );
      })}
    </ol>
  );
}
