"use server";

import { z } from "zod";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { requireUser, requirePermission } from "@/lib/auth/session";
import { checkConversationAccess, ensureConversation } from "@/lib/queries/conversations";
import { loadOwnedSession } from "./sessions";

export type MessageState = { error?: string } | undefined;

const messageSchema = z.object({ body: z.string().trim().min(1, "Message vide").max(10_000, "Message trop long") });

// Envoi d'un message par un humain, élève ou formateur.
// Les messages du moteur de process portent autoGenerated = true et pas d'expéditeur.
export async function sendMessage(conversationId: string, body: string): Promise<MessageState> {
  const me = await requireUser();
  const access = await checkConversationAccess(conversationId, me);
  // 404 côté appelant plutôt que 403 : on ne révèle pas l'existence du fil.
  if (!access.allowed) return { error: "Conversation introuvable." };

  const parsed = messageSchema.safeParse({ body });
  if (!parsed.success) return { error: parsed.error.issues[0].message };

  const conversation = await prisma.conversation.findUniqueOrThrow({
    where: { id: conversationId },
    select: { sessionId: true, session: { select: { status: true } } },
  });
  if (conversation.session.status === "cancelled") return { error: "Session annulée : la conversation est close." };

  await prisma.message.create({
    data: { conversationId, senderId: me.id, body: parsed.data.body, autoGenerated: false },
  });

  revalidatePath(`/admin/conversations/${conversationId}`);
  revalidatePath(`/admin/sessions/${conversation.sessionId}`);
  revalidatePath(`/espace/sessions/${conversation.sessionId}/messages`);
  return undefined;
}

// Ouvre (et crée si besoin) le fil d'un élève, côté formateur.
// Sert aux inscriptions antérieures à l'ouverture systématique des fils.
export async function openConversation(sessionId: string, userId: string) {
  const me = await requirePermission("can_manage_sessions");
  await loadOwnedSession(sessionId, me);
  const enrolled = await prisma.enrollment.count({ where: { sessionId, userId } });
  if (!enrolled) throw new Error("Élève non inscrit à cette session");
  const conversation = await ensureConversation(sessionId, userId);
  redirect(`/admin/conversations/${conversation.id}`);
}
