"use server";

import { z } from "zod";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { requireUser, requirePermission } from "@/lib/auth/session";
import { checkConversationAccess, ensureConversation } from "@/lib/queries/conversations";
import { createUploadUrl, ensureBucket } from "@/lib/storage/client";
import { MESSAGE_BUCKET, MAX_FILE_BYTES, isAllowedMessageType, safeFileName, formatBytes } from "@/lib/storage/config";
import type { MessageFile } from "@/lib/content/message-payload";
import { randomUUID } from "node:crypto";
import { loadOwnedSession } from "./sessions";

export type MessageState = { error?: string } | undefined;

const messageSchema = z.object({ body: z.string().trim().max(10_000, "Message trop long") });

const fileSchema = z.object({
  path: z.string().min(1),
  name: z.string().min(1),
  mimeType: z.string(),
  sizeBytes: z.number().int().min(1).max(MAX_FILE_BYTES),
});

// Autorisation d'envoi d'une pièce jointe. Le fichier ne transite pas par le
// serveur : le navigateur l'envoie directement au stockage privé, muni d'un
// jeton à usage unique délivré seulement après vérification des droits.
export type MessageUploadTicket = { ok: true; signedUrl: string; token: string; path: string } | { ok: false; error: string };

export async function requestMessageUpload(
  conversationId: string,
  fileName: string,
  mimeType: string,
  sizeBytes: number,
): Promise<MessageUploadTicket> {
  const me = await requireUser();
  const access = await checkConversationAccess(conversationId, me);
  if (!access.allowed) return { ok: false, error: "Conversation introuvable." };
  if (!isAllowedMessageType(mimeType)) return { ok: false, error: `Type de fichier non accepté (${mimeType || "inconnu"}).` };
  if (sizeBytes <= 0) return { ok: false, error: "Fichier vide." };
  if (sizeBytes > MAX_FILE_BYTES) return { ok: false, error: `Fichier trop lourd (${formatBytes(sizeBytes)}), maximum ${formatBytes(MAX_FILE_BYTES)}.` };

  const path = `conversations/${conversationId}/${randomUUID()}-${safeFileName(fileName)}`;
  try {
    await ensureBucket(MESSAGE_BUCKET);
    const ticket = await createUploadUrl(path, MESSAGE_BUCKET);
    return { ok: true, ...ticket };
  } catch (e) {
    return { ok: false, error: e instanceof Error ? e.message : "Envoi impossible." };
  }
}

// Envoi d'un message par un humain, élève ou formateur.
// Les messages du moteur de process portent autoGenerated = true et pas d'expéditeur.
export async function sendMessage(conversationId: string, body: string, files: MessageFile[] = []): Promise<MessageState> {
  const me = await requireUser();
  const access = await checkConversationAccess(conversationId, me);
  // 404 côté appelant plutôt que 403 : on ne révèle pas l'existence du fil.
  if (!access.allowed) return { error: "Conversation introuvable." };

  const parsed = messageSchema.safeParse({ body });
  if (!parsed.success) return { error: parsed.error.issues[0].message };

  const parsedFiles = z.array(fileSchema).max(5, "Cinq pièces jointes au maximum").safeParse(files);
  if (!parsedFiles.success) return { error: parsedFiles.error.issues[0].message };
  // Un message sans texte ni pièce n'a rien à dire.
  if (!parsed.data.body && parsedFiles.data.length === 0) return { error: "Message vide" };

  // Le chemin est imposé par le ticket : on refuse tout fichier déposé ailleurs,
  // sinon on pourrait joindre le fichier d'une autre conversation.
  const prefix = `conversations/${conversationId}/`;
  if (parsedFiles.data.some((f) => !f.path.startsWith(prefix))) return { error: "Pièce jointe invalide." };

  const conversation = await prisma.conversation.findUniqueOrThrow({
    where: { id: conversationId },
    select: { sessionId: true, session: { select: { status: true } } },
  });
  if (conversation.session.status === "cancelled") return { error: "Session annulée : la conversation est close." };

  await prisma.message.create({
    data: {
      conversationId, senderId: me.id, body: parsed.data.body, autoGenerated: false,
      ...(parsedFiles.data.length > 0 ? { attachments: { files: parsedFiles.data } } : {}),
    },
  });

  revalidatePath(`/admin/conversations/${conversationId}`);
  revalidatePath(`/admin/sessions/${conversation.sessionId}`);
  revalidatePath(`/espace/sessions/${conversation.sessionId}/messages`);
  return undefined;
}

// Ouvre (et crée si besoin) le fil d'un élève, côté formateur.
// Sert aux inscriptions antérieures à l'ouverture systématique des fils.
export async function openConversation(sessionId: string, userId: string) {
  const me = await requirePermission("can_manage_sessions");
  await loadOwnedSession(sessionId, me);
  const enrolled = await prisma.enrollment.count({ where: { sessionId, userId } });
  if (!enrolled) throw new Error("Élève non inscrit à cette session");
  const conversation = await ensureConversation(sessionId, userId);
  redirect(`/admin/conversations/${conversation.id}`);
}
