import { prisma } from "@/lib/prisma";
import { Prose } from "./prose";
import { formatDateTime } from "@/lib/format";
import { StatusBadge } from "@/components/admin/status-badge";
import { cn } from "@/lib/utils";
import { MessageComposer } from "./message-composer";
import Link from "next/link";
import { readMessageFiles } from "@/lib/content/message-payload";
import { formatBytes, documentLabel } from "@/lib/storage/config";

type Delivery = { kind?: string; sentTo?: string; sandbox?: boolean };

// Fil de discussion d'un élève sur une session (spec §5.8).
// Les mails déposés par le moteur de process (palier 3) y figurent au même
// endroit que les messages humains, marqués « Automatique ».
export async function MessageThread({
  conversationId,
  viewerId,
  readOnly = false,
  showDelivery = false,
}: {
  conversationId: string;
  viewerId: string;
  /// Session annulée : le fil reste lisible mais on n'écrit plus.
  readOnly?: boolean;
  /// Côté formateur seulement : à quelle adresse le mail est réellement parti.
  showDelivery?: boolean;
}) {
  const messages = await prisma.message.findMany({
    where: { conversationId },
    include: { sender: { select: { id: true, name: true } } },
    orderBy: { sentAt: "asc" },
  });

  return (
    <div className="space-y-4">
      {messages.length === 0 ? (
        <p className="rounded-lg border border-dashed px-4 py-10 text-center text-sm text-foreground-secondary">
          Aucun message pour l&apos;instant.
        </p>
      ) : (
        <ol className="space-y-3">
          {messages.map((m) => {
            const mine = m.senderId === viewerId;
            const auto = m.autoGenerated;
            const delivery = (m.attachments ?? {}) as Delivery;
            const attached = readMessageFiles(m.attachments);
            return (
              <li key={m.id} className={cn("flex", mine ? "justify-end" : "justify-start")}>
                <div
                  className={cn(
                    "max-w-[85%] min-w-0 rounded-lg border px-4 py-3",
                    mine ? "border-brand/30 bg-brand-soft" : auto ? "bg-surface" : "bg-background",
                  )}
                >
                  <p className="mb-1.5 flex flex-wrap items-center gap-x-2 gap-y-1 text-xs text-foreground-secondary">
                    <span className="font-medium text-foreground">
                      {auto ? "Message automatique" : mine ? "Vous" : (m.sender?.name ?? "—")}
                    </span>
                    <span>{formatDateTime(m.sentAt)}</span>
                    {auto ? <StatusBadge tone="blue">Automatique</StatusBadge> : null}
                    {showDelivery && delivery.sandbox ? <StatusBadge tone="yellow">Bac à sable</StatusBadge> : null}
                  </p>
                  {m.body.trim() ? <Prose markdown={m.body} className="text-sm" /> : null}
                  {attached.length > 0 ? (
                    <ul className={cn("space-y-1", m.body.trim() && "mt-2")}>
                      {attached.map((f, i) => {
                        const src = `/api/messages/${m.id}/fichier?i=${i}`;
                        const isImage = f.mimeType.startsWith("image/");
                        const isPdf = f.mimeType === "application/pdf";
                        return (
                          <li key={f.path} className="rounded-md border bg-background px-3 py-2 text-sm">
                            <div className="flex flex-wrap items-center justify-between gap-3">
                              <span className="min-w-0">
                                <span className="block truncate font-medium">{f.name}</span>
                                <span className="text-xs text-foreground-tertiary">
                                  {isImage ? "Image" : isPdf ? "PDF" : documentLabel(f.mimeType)} · {formatBytes(f.sizeBytes)}
                                </span>
                              </span>
                              <span className="flex shrink-0 gap-3 text-sm">
                                {isImage || isPdf ? (
                                  <Link href={src} target="_blank" rel="noopener noreferrer" className="underline underline-offset-2">Ouvrir</Link>
                                ) : null}
                                <Link href={`${src}&download=1`} className="text-foreground-secondary underline underline-offset-2 hover:text-foreground">
                                  Télécharger
                                </Link>
                              </span>
                            </div>
                          </li>
                        );
                      })}
                    </ul>
                  ) : null}
                  {showDelivery && delivery.kind === "email" ? (
                    <p className="mt-2 border-t pt-2 text-xs text-foreground-tertiary">
                      Envoyé par courriel à {delivery.sentTo ?? "—"}
                    </p>
                  ) : null}
                </div>
              </li>
            );
          })}
        </ol>
      )}

      {readOnly ? (
        <p className="rounded-md bg-surface px-3 py-2 text-sm text-foreground-secondary">
          Session annulée : la conversation est close. L&apos;historique reste consultable.
        </p>
      ) : (
        <MessageComposer conversationId={conversationId} />
      )}
    </div>
  );
}
