import "server-only";

import { prisma } from "@/lib/prisma";
import { sendMail } from "@/lib/mail/send";
import { isSandbox } from "@/lib/mail/config";
import { renderMessage } from "@/lib/messages/render";
import { MESSAGE_NOTIFICATION_TEMPLATE } from "@/lib/messages/notification";
import { appUrl } from "@/lib/app-url";

// ═══════════════════════════════════════════════════════════════════════════
// NOTIFICATION DES MESSAGES NON LUS
//
// Le mail n'est pas le canal, c'est le rattrapage : personne n'est prévenu
// d'un message qu'il a déjà vu sur la plateforme.
//
// Un message n'est notifié que si, au moment du passage :
//   1. le destinataire n'a pas ouvert le fil depuis qu'il est arrivé,
//   2. il a au moins QUIET_MINUTES (le temps qu'une salve se termine),
//   3. aucune notification ne l'a déjà couvert,
//   4. la session n'est ni annulée ni de démonstration.
// Tous les messages en attente d'un même fil partent dans UN SEUL mail, et une
// personne ne reçoit pas plus d'un mail par fil et par COOLDOWN_HOURS.
// ═══════════════════════════════════════════════════════════════════════════

const QUIET_MINUTES = 15;
const COOLDOWN_HOURS = 24;
/// Au-delà, un message non lu ne déclenche plus rien : on ne réveille pas un
/// fil vieux d'un trimestre.
const WINDOW_DAYS = 30;

export type NotificationReport = {
  pending: number;
  notified: number;
  failed: number;
  skipped: string[];
  sandbox: boolean;
  dryRun: boolean;
  details: { to: string; label: string; count: number; ok: boolean; error?: string }[];
};

const firstName = (full: string) => full.trim().split(/\s+/)[0] ?? full;

export async function runMessageNotifications(options: { dryRun?: boolean } = {}): Promise<NotificationReport> {
  const dryRun = options.dryRun ?? false;
  const now = new Date();
  const report: NotificationReport = {
    pending: 0, notified: 0, failed: 0, skipped: [], sandbox: isSandbox(), dryRun, details: [],
  };

  const candidates = await prisma.message.findMany({
    where: {
      notifiedAt: null,
      autoGenerated: false,
      senderId: { not: null },
      sentAt: {
        lte: new Date(now.getTime() - QUIET_MINUTES * 60_000),
        gte: new Date(now.getTime() - WINDOW_DAYS * 24 * 3600_000),
      },
      conversation: { session: { isDemo: false, status: { not: "cancelled" } } },
    },
    orderBy: { sentAt: "asc" },
    select: {
      id: true,
      senderId: true,
      sentAt: true,
      sender: { select: { id: true, name: true } },
      conversation: {
        select: {
          id: true,
          userId: true,
          user: { select: { id: true, name: true, email: true } },
          session: {
            select: {
              id: true,
              name: true,
              trainer: { select: { id: true, name: true, email: true } },
              owner: { select: { id: true, name: true, email: true } },
              formationVersion: { select: { formation: { select: { name: true } } } },
            },
          },
        },
      },
    },
  });
  report.pending = candidates.length;
  if (candidates.length === 0) return report;

  // Un groupe = un fil × un destinataire. L'élève écrit → le formateur est
  // prévenu ; le formateur écrit → l'élève l'est.
  type Group = {
    conversationId: string;
    sessionId: string;
    sessionName: string;
    formationName: string;
    recipient: { id: string; name: string; email: string };
    isStudent: boolean;
    senderNames: Set<string>;
    messageIds: string[];
    lastSentAt: Date;
  };
  const groups = new Map<string, Group>();

  for (const message of candidates) {
    const { conversation } = message;
    const student = conversation.user;
    const staff = conversation.session.trainer ?? conversation.session.owner;
    const toStaff = message.senderId === student.id;
    const recipient = toStaff ? staff : student;

    if (!recipient?.email) {
      report.skipped.push(`Session « ${conversation.session.name} » : destinataire sans email.`);
      continue;
    }
    // Un message écrit par le destinataire lui-même ne se notifie pas.
    if (recipient.id === message.senderId) continue;

    const key = `${conversation.id}:${recipient.id}`;
    const group = groups.get(key) ?? {
      conversationId: conversation.id,
      sessionId: conversation.session.id,
      sessionName: conversation.session.name,
      formationName: conversation.session.formationVersion.formation.name,
      recipient: { id: recipient.id, name: recipient.name, email: recipient.email },
      isStudent: !toStaff,
      senderNames: new Set<string>(),
      messageIds: [],
      lastSentAt: message.sentAt,
    };
    group.messageIds.push(message.id);
    group.senderNames.add(message.sender?.name ?? "—");
    if (message.sentAt > group.lastSentAt) group.lastSentAt = message.sentAt;
    groups.set(key, group);
  }

  const cooldownStart = new Date(now.getTime() - COOLDOWN_HOURS * 3600_000);

  for (const group of groups.values()) {
    const state = await prisma.conversationRead.findUnique({
      where: { conversationId_userId: { conversationId: group.conversationId, userId: group.recipient.id } },
      select: { readAt: true, notifiedAt: true },
    });

    // Déjà vu sur la plateforme : aucun mail. On marque les messages comme
    // traités pour ne pas les réexaminer à chaque passage.
    if (state?.readAt && state.readAt >= group.lastSentAt) {
      if (!dryRun) {
        await prisma.message.updateMany({ where: { id: { in: group.messageIds } }, data: { notifiedAt: now } });
      }
      report.skipped.push(`${group.recipient.name} a déjà lu le fil « ${group.sessionName} ».`);
      continue;
    }
    // Déjà prévenu récemment et toujours pas revenu : on attend plutôt que de
    // relancer. Le délai se remet à zéro dès qu'il ouvre le fil, pour qu'un
    // destinataire actif ne rate pas la suite de la conversation.
    const notifiedRecently = state?.notifiedAt && state.notifiedAt > cooldownStart;
    const readSinceNotice = state?.readAt && state.notifiedAt && state.readAt > state.notifiedAt;
    if (notifiedRecently && !readSinceNotice) {
      report.skipped.push(`${group.recipient.name} : déjà prévenu il y a moins de ${COOLDOWN_HOURS} h, sans être revenu.`);
      continue;
    }

    const count = group.messageIds.length;
    const senders = [...group.senderNames];
    const values: Record<string, string> = {
      compte: count === 1 ? "Nouveau message" : `${count} nouveaux messages`,
      compte_minuscule: count === 1 ? "ce message" : "ces messages",
      "destinataire.prenom": firstName(group.recipient.name),
      "expediteur.nom": senders.length === 1 ? senders[0] : senders.join(", "),
      "formation.nom": group.formationName,
      "session.nom": group.sessionName,
      lien_fil: group.isStudent
        ? appUrl(`/espace/sessions/${group.sessionId}/messages`)
        : appUrl(`/admin/conversations/${group.conversationId}`),
      rappel: group.isStudent
        ? ""
        : "Ce rappel ne part qu'une fois par jour et par fil, tant que les messages ne sont pas lus.",
    };
    const rendered = renderMessage(MESSAGE_NOTIFICATION_TEMPLATE, values);

    if (dryRun) {
      report.notified++;
      report.details.push({ to: group.recipient.email, label: group.recipient.name, count, ok: true });
      continue;
    }

    const result = await sendMail({
      intendedTo: group.recipient.email,
      subject: rendered.subject,
      html: rendered.html,
      text: rendered.text,
    });

    if (!result.ok) {
      report.failed++;
      report.details.push({ to: group.recipient.email, label: group.recipient.name, count, ok: false, error: result.error });
      continue;
    }

    // Marqué seulement après un envoi réussi : un échec sera retenté au passage suivant.
    await prisma.$transaction([
      prisma.message.updateMany({ where: { id: { in: group.messageIds } }, data: { notifiedAt: now } }),
      prisma.conversationRead.upsert({
        where: { conversationId_userId: { conversationId: group.conversationId, userId: group.recipient.id } },
        create: { conversationId: group.conversationId, userId: group.recipient.id, notifiedAt: now },
        update: { notifiedAt: now },
      }),
    ]);
    report.notified++;
    report.details.push({ to: result.sentTo, label: group.recipient.name, count, ok: true });
  }

  return report;
}
