import Link from "next/link";
import { redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { requireUser, hasPermission } from "@/lib/auth/session";
import { canSupervise } from "@/lib/auth/ownership";
import { formatDateTime } from "@/lib/format";
import { PageHeader } from "@/components/admin/page-header";
import { StatusBadge } from "@/components/admin/status-badge";
import { EmptyState } from "@/components/admin/empty-state";

// Tous mes fils, le plus récent d'abord : un fil par élève et par session.
export default async function ConversationsInboxPage() {
  const me = await requireUser("/admin/conversations");
  if (!hasPermission(me, "can_manage_sessions")) redirect("/admin");

  const sessionScope = canSupervise(me) ? {} : { OR: [{ ownerId: me.id }, { trainerId: me.id }] };
  const conversations = await prisma.conversation.findMany({
    where: { session: sessionScope },
    select: {
      id: true,
      userId: true,
      user: { select: { name: true } },
      session: { select: { id: true, name: true, isDemo: true } },
      _count: { select: { messages: true } },
      messages: { orderBy: { sentAt: "desc" }, take: 1, select: { body: true, sentAt: true, senderId: true, autoGenerated: true } },
    },
    take: 200,
  });

  // Tri applicatif : la date du dernier message n'est pas une colonne du fil.
  const rows = conversations
    .map((c) => ({ ...c, last: c.messages[0] ?? null }))
    .sort((a, b) => (b.last?.sentAt.getTime() ?? 0) - (a.last?.sentAt.getTime() ?? 0));

  return (
    <div className="space-y-8">
      <PageHeader
        title="Messages"
        description="Un fil par élève et par session. Les envois automatiques y figurent aussi."
      />

      {rows.length === 0 ? (
        <EmptyState title="Aucun fil pour l&apos;instant">Les fils s&apos;ouvrent dès qu&apos;un élève est inscrit à une session.</EmptyState>
      ) : (
        <ol className="divide-y rounded-md border">
          {rows.map((c) => {
            const waiting = c.last?.senderId === c.userId;
            const excerpt = c.last ? c.last.body.replace(/[*_#>`]/g, " ").replace(/\s+/g, " ").trim().slice(0, 120) : null;
            return (
              <li key={c.id}>
                <Link href={`/admin/conversations/${c.id}`} className="flex items-start justify-between gap-4 px-4 py-3 text-sm transition-colors hover:bg-surface">
                  <span className="min-w-0">
                    <span className="flex flex-wrap items-center gap-2">
                      <span className="font-medium">{c.user.name}</span>
                      <span className="text-foreground-tertiary">{c.session.name}</span>
                      {waiting ? <StatusBadge tone="orange">À lire</StatusBadge> : null}
                      {c.session.isDemo ? <StatusBadge tone="orange">Démo</StatusBadge> : null}
                    </span>
                    <span className="mt-0.5 block truncate text-xs text-foreground-secondary">
                      {excerpt && c.last ? `${c.last.autoGenerated ? "Automatique · " : ""}${excerpt}` : "Aucun message"}
                    </span>
                  </span>
                  <span className="shrink-0 text-right text-xs text-foreground-tertiary">
                    {c.last ? <>{formatDateTime(c.last.sentAt)}<span className="block">{c._count.messages} message(s)</span></> : "—"}
                  </span>
                </Link>
              </li>
            );
          })}
        </ol>
      )}
    </div>
  );
}
